Enhance version update logic in CI workflow for pyproject.toml
Changes:
- Added validation for the Git tag format before updating the version in pyproject.toml.
- Improved error handling to exit with a message if the tag format is invalid.

diff --git a/.github/workflows/publish-to-pypi.yaml b/.github/workflows/publish-to-pypi.yaml
--- a/.github/workflows/publish-to-pypi.yaml
+++ b/.github/workflows/publish-to-pypi.yaml
@@ -30,10 +30,16 @@ jobs:
         run: |
           TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
           echo "tag=$TAG" >> $GITHUB_ENV
-
       - name: Update version
         run: |
-          sed -i "s/^version = .*/version = \"$TAG\"/" pyproject.toml
+          TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
+          if [[ $TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+            VERSION=${TAG#v} # Remove the 'v' prefix
+            sed -i "s/^version = .*/version = \"$VERSION\"/" pyproject.toml
+          else
+            echo "Invalid tag format. Expected format: v<MAJOR>.<MINOR>.<PATCH>"
+            exit 1
+          fi
 
       - name: Build
         run: uv build
